# Generated by Django 5.0.8 on 2024-08-22 20:27

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0019_alter_numeriquebasepage_body"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True, verbose_name="Category name")),
                ("slug", models.SlugField(max_length=80, unique=True)),
            ],
            options={
                "verbose_name": "Offer Category",
            },
        ),
        migrations.CreateModel(
            name="OffersIndexPage",
            fields=[
                (
                    "numeriquebasepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="numerique_gouv.numeriquebasepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offers index",
            },
            bases=("numerique_gouv.numeriquebasepage",),
        ),
        migrations.CreateModel(
            name="OfferTargetAudience",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True, verbose_name="Category name")),
                ("slug", models.SlugField(max_length=80, unique=True)),
            ],
            options={
                "verbose_name": "Offer Target Audience",
            },
        ),
        migrations.CreateModel(
            name="OfferTheme",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True, verbose_name="Category name")),
                ("slug", models.SlugField(max_length=80, unique=True)),
            ],
            options={
                "verbose_name": "Offer Theme",
            },
        ),
        migrations.CreateModel(
            name="Offertype",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True, verbose_name="Category name")),
                ("slug", models.SlugField(max_length=80, unique=True)),
            ],
            options={
                "verbose_name": "Offer Type",
            },
        ),
        migrations.CreateModel(
            name="OffersEntryPage",
            fields=[
                (
                    "numeriquebasepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="numerique_gouv.numeriquebasepage",
                    ),
                ),
                ("card_description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "card_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Card image",
                    ),
                ),
                (
                    "categories",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="numerique_gouv.offercategory", verbose_name="Categories"
                    ),
                ),
                (
                    "target_audience",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="numerique_gouv.offertargetaudience", verbose_name="Target Audience"
                    ),
                ),
                (
                    "theme",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="numerique_gouv.offertheme", verbose_name="Theme"
                    ),
                ),
                (
                    "type",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="numerique_gouv.offertype", verbose_name="Type"
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer page",
            },
            bases=("numerique_gouv.numeriquebasepage",),
        ),
    ]
