# Generated by Django 5.0.8 on 2024-08-22 20:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0021_offercategory_color_offertargetaudience_color_and_more"),
    ]
