# Generated by Django 5.0.8 on 2024-08-22 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0022_offersentrypage_introductory_text"),
    ]
