# Generated by Django 5.0.8 on 2024-08-25 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0023_remove_offersentrypage_introductory_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offersentrypage",
            old_name="target_audience",
            new_name="target_audiences",
        ),
        migrations.RenameField(
            model_name="offersentrypage",
            old_name="theme",
            new_name="themes",
        ),
        migrations.RenameField(
            model_name="offersentrypage",
            old_name="type",
            new_name="types",
        ),
    ]
