# Generated by Django 5.0.8 on 2024-08-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0024_rename_target_audience_offersentrypage_target_audiences_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offersentrypage",
            name="introductory_text",
            field=models.TextField(blank=True, verbose_name="Introductory text"),
        ),
    ]
