# Generated by Django 5.0.8 on 2024-08-25 21:07

import numerique_gouv.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0025_offersentrypage_introductory_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offersentrypage",
            name="introductory_text",
        ),
        migrations.AddField(
            model_name="offersentrypage",
            name="text_and_cta",
            field=numerique_gouv.models.TextAndCTAStreamField(blank=True, verbose_name=("Text and CTA")),
        ),
    ]
