# Generated by Django 5.0.8 on 2024-08-25 21:42

import django.db.models.deletion
import numerique_gouv.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0027_remove_offersentrypage_text_and_cta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offersentrypage",
            name="types",
        ),
        migrations.AddField(
            model_name="offersentrypage",
            name="text_and_cta",
            field=numerique_gouv.models.TextAndCTAStreamField(
                [("text_and_cta", 13)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"label": "Rich text", "required": False}),
                    1: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Link to a page of this site. Use either this, the document, or the external URL parameter.",
                            "label": "Page",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Use either this, the external URL or the page parameter.",
                            "label": "Document",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use either this, the document or the page parameter.",
                            "label": "External URL",
                            "required": False,
                        },
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Link label", "required": False}),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fr-btn", "Primary"),
                                ("fr-btn fr-btn--secondary", "Secundary"),
                                ("fr-btn fr-btn--tertiary", "Tertiary"),
                                ("fr-btn fr-btn--tertiary-no-outline", "Tertiary without border"),
                            ],
                            "label": "Button type",
                            "required": False,
                        },
                    ),
                    6: ("content_manager.blocks.IconPickerBlock", (), {"label": "Icon", "required": False}),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("fr-btn--icon-left", "Left"), ("fr-btn--icon-right", "Right")],
                            "label": "Icon side",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page", 1),
                                ("document", 2),
                                ("external_url", 3),
                                ("text", 4),
                                ("button_type", 5),
                                ("icon_class", 6),
                                ("icon_side", 7),
                            ]
                        ],
                        {"label": "Button"},
                    ),
                    9: (
                        "wagtail.blocks.StreamBlock",
                        [[("button", 8)]],
                        {
                            "help_text": "Please use only one primary button. If you use icons, align them on the same side."
                        },
                    ),
                    10: (
                        "wagtail.blocks.StreamBlock",
                        [[("buttons", 9)]],
                        {"label": "Call-to-action buttons", "max_num": 1, "required": False},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "This field is obsolete and will be removed in the near future. Please replace with the CTA buttons above.",
                            "label": "Call to action label  (obsolete)",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "This field is obsolete and will be removed in the near future. Please replace with the CTA buttons above.",
                            "label": "Link (obsolete)",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("cta_buttons", 10), ("cta_label", 11), ("cta_url", 12)]],
                        {},
                    ),
                },
                verbose_name="Text and CTA",
            ),
        ),
        migrations.AddField(
            model_name="offersentrypage",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="numerique_gouv.offertype",
                verbose_name="Type",
            ),
        ),
    ]
