# Generated by Django 5.0.8 on 2024-08-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0028_remove_offersentrypage_types_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offersentrypage",
            name="block_one_column_one",
            field=models.TextField(blank=True, verbose_name="Block one column one"),
        ),
        migrations.AddField(
            model_name="offersentrypage",
            name="block_one_column_three",
            field=models.TextField(blank=True, verbose_name="Block one column three"),
        ),
        migrations.AddField(
            model_name="offersentrypage",
            name="block_one_column_two",
            field=models.TextField(blank=True, verbose_name="Block one column two"),
        ),
        migrations.AddField(
            model_name="offersentrypage",
            name="block_one_title",
            field=models.TextField(blank=True, verbose_name="Block one title"),
        ),
        migrations.AddField(
            model_name="offersentrypage",
            name="block_three_column_one",
            field=models.TextField(blank=True, verbose_name="Block three column one"),
        ),
        migrations.AddField(
            model_name="offersentrypage",
            name="block_three_column_three",
            field=models.TextField(blank=True, verbose_name="Block three column three"),
        ),
        migrations.AddField(
            model_name="offersentrypage",
            name="block_three_column_two",
            field=models.TextField(blank=True, verbose_name="Block three column two"),
        ),
        migrations.AddField(
            model_name="offersentrypage",
            name="block_three_subtitle",
            field=models.TextField(blank=True, verbose_name="Block three subtitle"),
        ),
        migrations.AddField(
            model_name="offersentrypage",
            name="block_three_title",
            field=models.TextField(blank=True, verbose_name="Block three title"),
        ),
        migrations.AddField(
            model_name="offersentrypage",
            name="block_two_column_one",
            field=models.TextField(blank=True, verbose_name="Block two column one"),
        ),
        migrations.AddField(
            model_name="offersentrypage",
            name="block_two_column_three",
            field=models.TextField(blank=True, verbose_name="Block two column three"),
        ),
        migrations.AddField(
            model_name="offersentrypage",
            name="block_two_column_two",
            field=models.TextField(blank=True, verbose_name="Block two column two"),
        ),
        migrations.AddField(
            model_name="offersentrypage",
            name="block_two_title",
            field=models.TextField(blank=True, verbose_name="Block two title"),
        ),
        migrations.AddField(
            model_name="offersentrypage",
            name="organization_title",
            field=models.TextField(blank=True, verbose_name="Organization title"),
        ),
    ]
