# Generated by Django 5.0.8 on 2024-08-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0029_offersentrypage_block_one_column_one_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offersentrypage",
            name="card_texte",
            field=models.TextField(blank=True, verbose_name="Text"),
        ),
    ]
