# Generated by Django 5.0.8 on 2024-08-28 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0030_offersentrypage_card_texte"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offersentrypage",
            old_name="card_texte",
            new_name="card_text",
        ),
    ]
