# Generated by Django 5.0.8 on 2024-08-30 12:53

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0032_alter_numeriquebasepage_body"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True, verbose_name="Category name")),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("green-tilleul-verveine", "Tilleul verveine"),
                            ("green-bourgeon", "Bourgeon"),
                            ("green-emeraude", "Émeraude"),
                            ("green-menthe", "Menthe"),
                            ("green-archipel", "Archipel"),
                            ("blue-ecume", "Écume"),
                            ("blue-cumulus", "Cumulus"),
                            ("purple-glycine", "Glycine"),
                            ("pink-macaron", "Macaron"),
                            ("pink-tuile", "Tuile"),
                            ("yellow-tournesol", "Tournesol"),
                            ("yellow-moutarde", "Moutarde"),
                            ("orange-terre-battue", "Terre battue"),
                            ("brown-cafe-creme", "Café crème"),
                            ("brown-caramel", "Caramel"),
                            ("brown-opera", "Opéra"),
                            ("beige-gris-galet", "Gris galet"),
                        ],
                        default="blue",
                        verbose_name="Color",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Category",
            },
        ),
        migrations.CreateModel(
            name="ProductsIndexPage",
            fields=[
                (
                    "numeriquebasepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="numerique_gouv.numeriquebasepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Products index",
            },
            bases=("numerique_gouv.numeriquebasepage",),
        ),
        migrations.CreateModel(
            name="ProductTargetAudience",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True, verbose_name="Category name")),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("green-tilleul-verveine", "Tilleul verveine"),
                            ("green-bourgeon", "Bourgeon"),
                            ("green-emeraude", "Émeraude"),
                            ("green-menthe", "Menthe"),
                            ("green-archipel", "Archipel"),
                            ("blue-ecume", "Écume"),
                            ("blue-cumulus", "Cumulus"),
                            ("purple-glycine", "Glycine"),
                            ("pink-macaron", "Macaron"),
                            ("pink-tuile", "Tuile"),
                            ("yellow-tournesol", "Tournesol"),
                            ("yellow-moutarde", "Moutarde"),
                            ("orange-terre-battue", "Terre battue"),
                            ("brown-cafe-creme", "Café crème"),
                            ("brown-caramel", "Caramel"),
                            ("brown-opera", "Opéra"),
                            ("beige-gris-galet", "Gris galet"),
                        ],
                        default="blue",
                        verbose_name="Color",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Target Audience",
            },
        ),
        migrations.CreateModel(
            name="ProductsEntryPage",
            fields=[
                (
                    "numeriquebasepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="numerique_gouv.numeriquebasepage",
                    ),
                ),
                ("product_url", models.URLField(blank=True, verbose_name="Product URL")),
                ("the_service", models.TextField(blank=True, verbose_name="The service")),
                ("the_problem", models.TextField(blank=True, verbose_name="The problem")),
                (
                    "categories",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="numerique_gouv.offercategory", verbose_name="Categories"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Card image",
                    ),
                ),
                (
                    "target_audience",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="numerique_gouv.producttargetaudience",
                        verbose_name="Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product page",
            },
            bases=("numerique_gouv.numeriquebasepage",),
        ),
    ]
