# Generated by Django 5.0.8 on 2024-08-30 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0033_productcategory_productsindexpage_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductCategory",
        ),
    ]
