# Generated by Django 5.0.8 on 2024-08-30 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0036_alter_pagetag_options_productsentrypage_image_alt_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productsentrypage",
            old_name="categories",
            new_name="tags",
        ),
    ]
