# Generated by Django 5.0.8 on 2024-09-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0037_rename_categories_productsentrypage_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offersentrypage",
            name="card_description",
        ),
        migrations.AddField(
            model_name="offersentrypage",
            name="card_alt_image",
            field=models.CharField(blank=True, max_length=255, verbose_name="Image alt"),
        ),
    ]
