# Generated by Django 5.0.8 on 2024-09-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0038_remove_offersentrypage_card_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offersentrypage",
            name="card_description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
    ]
