# Generated by Django 5.0.8 on 2024-09-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0040_alter_numeriquebasepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsentrypage",
            name="position",
            field=models.IntegerField(default=0),
        ),
    ]
