# Generated by Django 5.0.9 on 2024-09-13 09:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0045_alter_targetaudience_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offersentrypage",
            old_name="target_audiences",
            new_name="target_audiences_old",
        ),
    ]
