# Generated by Django 5.0.9 on 2024-09-13 09:18

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0046_rename_target_audiences_offersentrypage_target_audiences_old"),
    ]

    operations = [
        migrations.AddField(
            model_name="offersentrypage",
            name="target_audiences",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="numerique_gouv.targetaudience", verbose_name="Target Audience"
            ),
        ),
    ]
