# Generated by Django 5.0.9 on 2024-09-13 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0047_offersentrypage_target_audiences"),
        ("numerique_gouv", "0048_migrate_target_audiences_old_to_target_audiences"),
    ]

    operations = []
