# Generated by Django 5.0.9 on 2024-09-13 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0049_merge_20240913_1121"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OfferTheme",
            new_name="DinumTag",
        ),
    ]
