# Generated by Django 5.0.9 on 2024-09-13 12:45

import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0050_rename_offertheme_to_majorarea"),
    ]

    operations = [
        migrations.CreateModel(
            name="MajorArea",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True, verbose_name="Category name")),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("green-tilleul-verveine", "Tilleul verveine"),
                            ("green-bourgeon", "Bourgeon"),
                            ("green-emeraude", "Émeraude"),
                            ("green-menthe", "Menthe"),
                            ("green-archipel", "Archipel"),
                            ("blue-ecume", "Écume"),
                            ("blue-cumulus", "Cumulus"),
                            ("purple-glycine", "Glycine"),
                            ("pink-macaron", "Macaron"),
                            ("pink-tuile", "Tuile"),
                            ("yellow-tournesol", "Tournesol"),
                            ("yellow-moutarde", "Moutarde"),
                            ("orange-terre-battue", "Terre battue"),
                            ("brown-cafe-creme", "Café crème"),
                            ("brown-caramel", "Caramel"),
                            ("brown-opera", "Opéra"),
                            ("beige-gris-galet", "Gris galet"),
                        ],
                        default="blue",
                        verbose_name="Color",
                    ),
                ),
            ],
            options={
                "verbose_name": "Major Area of Action",
            },
        ),
        migrations.AlterModelOptions(
            name="dinumtag",
            options={"verbose_name": "Dinum Tag"},
        ),
        migrations.AlterModelOptions(
            name="offertargetaudience",
            options={"verbose_name": "Offer Target Audience ( a supprimer )"},
        ),
        migrations.AddField(
            model_name="offersentrypage",
            name="major_area",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="numerique_gouv.majorarea", verbose_name="Dinum Tags"
            ),
        ),
    ]
