# Generated by Django 5.0.9 on 2024-09-13 13:26

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0051_majorarea_alter_dinumtag_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HubPages",
            fields=[
                (
                    "numeriquebasepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="numerique_gouv.numeriquebasepage",
                    ),
                ),
                ("display_actualites", models.BooleanField(default=True, verbose_name="Display actualites")),
                ("display_events", models.BooleanField(default=True, verbose_name="Display events")),
                ("display_products", models.BooleanField(default=True, verbose_name="Display products")),
                ("display_offers", models.BooleanField(default=True, verbose_name="Display offers")),
                (
                    "content_source",
                    models.CharField(
                        choices=[
                            ("major_areas", "Major Areas of Actions"),
                            ("dinum_tags", "Dinum Tags"),
                            ("tags", "Tags"),
                            ("target_audiences", "Target Audiences"),
                        ],
                        max_length=20,
                        verbose_name="Content Source",
                    ),
                ),
                (
                    "dinum_tags",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="numerique_gouv.dinumtag", verbose_name="Dinum Tags"
                    ),
                ),
                (
                    "major_areas",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="numerique_gouv.majorarea", verbose_name="Major Areas of Actions"
                    ),
                ),
                (
                    "tags",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="numerique_gouv.pagetag", verbose_name="Tags"
                    ),
                ),
                (
                    "target_audiences",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="numerique_gouv.targetaudience", verbose_name="Target Audiences"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hub page",
            },
            bases=("numerique_gouv.numeriquebasepage",),
        ),
    ]
