# Generated by Django 5.0.9 on 2024-09-17 19:26

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0039_alter_blogentrypage_body"),
        ("numerique_gouv", "0052_hubpages"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumeriqueBlogEntryPage",
            fields=[
                (
                    "blogentrypage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blog.blogentrypage",
                    ),
                ),
                (
                    "dinum_tags",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="numerique_gouv.dinumtag", verbose_name="Dinum Tags"
                    ),
                ),
                (
                    "major_areas",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="numerique_gouv.majorarea", verbose_name="Major Areas of Actions"
                    ),
                ),
                (
                    "page_tags",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="numerique_gouv.pagetag", verbose_name="Page tags"
                    ),
                ),
                (
                    "target_audiences",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="numerique_gouv.targetaudience", verbose_name="Target Audiences"
                    ),
                ),
            ],
            options={
                "verbose_name": "Numerique blog entry page",
            },
            bases=("blog.blogentrypage",),
        ),
    ]
