# Generated by Django 5.0.9 on 2024-09-17 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0039_alter_blogentrypage_body"),
        ("numerique_gouv", "0053_numeriqueblogentrypage"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumeriqueBlogIndexPage",
            fields=[
                (
                    "blogindexpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blog.blogindexpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Numerique blog index page",
            },
            bases=("blog.blogindexpage",),
        ),
    ]
