# Generated by Django 5.0.9 on 2024-09-19 16:56

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0054_numeriqueblogindexpage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productsentrypage",
            old_name="tags",
            new_name="page_tags",
        ),
        migrations.RenameField(
            model_name="offersentrypage",
            old_name="categories",
            new_name="page_tags",
        ),
    ]
