# Generated by Django 5.0.9 on 2024-09-23 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0057_remove_hubpages_tags_hubpages_page_tags_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hubpages",
            name="dinum_tags",
        ),
        migrations.RemoveField(
            model_name="hubpages",
            name="major_areas",
        ),
        migrations.RemoveField(
            model_name="hubpages",
            name="page_tags",
        ),
        migrations.RemoveField(
            model_name="hubpages",
            name="target_audiences",
        ),
        migrations.AddField(
            model_name="hubpages",
            name="dinum_tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="numerique_gouv.dinumtag",
                verbose_name="Dinum Tags",
            ),
        ),
        migrations.AddField(
            model_name="hubpages",
            name="major_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="numerique_gouv.majorarea",
                verbose_name="Major Area of Actions",
            ),
        ),
        migrations.AddField(
            model_name="hubpages",
            name="page_tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="numerique_gouv.pagetag",
                verbose_name="Page tags",
            ),
        ),
        migrations.AddField(
            model_name="hubpages",
            name="target_audience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="numerique_gouv.targetaudience",
                verbose_name="Target Audience",
            ),
        ),
        migrations.AlterField(
            model_name="hubpages",
            name="content_source",
            field=models.CharField(
                choices=[
                    ("major_area", "Major Areas of Actions"),
                    ("dinum_tag", "Dinum Tags"),
                    ("page_tag", "Page tags"),
                    ("target_audience", "Target Audiences"),
                ],
                max_length=20,
                verbose_name="Content Source",
            ),
        ),
    ]
