# Generated by Django 5.0.9 on 2024-10-15 18:40

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_alter_evententrypage_body_alter_eventsindexpage_body"),
        ("numerique_gouv", "0063_alter_numeriquebasepage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumeriqueEventPage",
            fields=[
                (
                    "numeriquebasepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="numerique_gouv.numeriquebasepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Numerique event page",
            },
            bases=("numerique_gouv.numeriquebasepage",),
        ),
        migrations.CreateModel(
            name="NumeriqueEventsIndexPage",
            fields=[
                (
                    "eventsindexpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.eventsindexpage",
                    ),
                ),
                (
                    "dinum_tags",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="numerique_gouv.dinumtag", verbose_name="Dinum Tags"
                    ),
                ),
                (
                    "major_areas",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="numerique_gouv.majorarea", verbose_name="Major Areas of Actions"
                    ),
                ),
                (
                    "page_tags",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="numerique_gouv.pagetag", verbose_name="Page tags"
                    ),
                ),
                (
                    "target_audiences",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="numerique_gouv.targetaudience", verbose_name="Target Audiences"
                    ),
                ),
            ],
            options={
                "verbose_name": "Numerique events index page",
            },
            bases=("events.eventsindexpage",),
        ),
    ]
