# Generated by Django 5.0.9 on 2024-10-15 18:46

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0064_numeriqueeventpage_numeriqueeventsindexpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="numeriqueeventsindexpage",
            name="dinum_tags",
        ),
        migrations.RemoveField(
            model_name="numeriqueeventsindexpage",
            name="major_areas",
        ),
        migrations.RemoveField(
            model_name="numeriqueeventsindexpage",
            name="page_tags",
        ),
        migrations.RemoveField(
            model_name="numeriqueeventsindexpage",
            name="target_audiences",
        ),
        migrations.AddField(
            model_name="numeriqueeventpage",
            name="dinum_tags",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="numerique_gouv.dinumtag", verbose_name="Dinum Tags"
            ),
        ),
        migrations.AddField(
            model_name="numeriqueeventpage",
            name="major_areas",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="numerique_gouv.majorarea", verbose_name="Major Areas of Actions"
            ),
        ),
        migrations.AddField(
            model_name="numeriqueeventpage",
            name="page_tags",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="numerique_gouv.pagetag", verbose_name="Page tags"
            ),
        ),
        migrations.AddField(
            model_name="numeriqueeventpage",
            name="target_audiences",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="numerique_gouv.targetaudience", verbose_name="Target Audiences"
            ),
        ),
    ]
