# Generated by Django 5.0.9 on 2024-10-15 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_alter_evententrypage_body_alter_eventsindexpage_body"),
        ("numerique_gouv", "0065_remove_numeriqueeventsindexpage_dinum_tags_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="numeriqueeventpage",
            name="numeriquebasepage_ptr",
        ),
        migrations.AddField(
            model_name="numeriqueeventpage",
            name="evententrypage_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="events.evententrypage",
            ),
            preserve_default=False,
        ),
    ]
