# Generated by Django 5.0.9 on 2024-10-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0069_alter_numeriquebasepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="offersentrypage",
            name="position",
            field=models.IntegerField(default=0),
        ),
    ]
