# Generated by Django 5.0.9 on 2024-11-15 10:45

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0051_alter_blogentrypage_body"),
        ("numerique_gouv", "0074_alter_numeriquebasepage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offersentrypage",
            name="target_audiences_old",
        ),
        migrations.AddField(
            model_name="offersentrypage",
            name="organizations",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="blog.organization", verbose_name="Organizations"
            ),
        ),
    ]
