# Generated by Django 5.0.9 on 2024-11-16 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0075_remove_offersentrypage_target_audiences_old_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offersentrypage",
            name="themes",
        ),
    ]
