# Generated by Django 5.0.9 on 2024-11-16 13:20

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0051_alter_blogentrypage_body"),
        ("numerique_gouv", "0076_remove_offersentrypage_themes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="numeriqueblogentrypage",
            name="dinum_tags",
        ),
        migrations.AddField(
            model_name="numeriqueblogentrypage",
            name="organizations",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="blog.organization", verbose_name="Organizations"
            ),
        ),
    ]
