# Generated by Django 5.0.9 on 2024-11-17 09:25

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0051_alter_blogentrypage_body"),
        ("numerique_gouv", "0078_remove_hubpages_dinum_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsentrypage",
            name="organizations",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="blog.organization", verbose_name="Organizations"
            ),
        ),
        migrations.AlterField(
            model_name="productsentrypage",
            name="page_tags",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="numerique_gouv.pagetag", verbose_name="Page tags"
            ),
        ),
    ]
