# Generated by Django 5.0.9 on 2024-11-17 19:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0079_productsentrypage_organizations_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dinumtag",
            options={"verbose_name": "Dinum Tag ( a supprimer )"},
        ),
    ]
