# Generated by Django 5.0.9 on 2024-11-23 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0080_alter_dinumtag_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SitemapPage",
            fields=[
                (
                    "numeriquebasepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="numerique_gouv.numeriquebasepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan du site",
            },
            bases=("numerique_gouv.numeriquebasepage",),
        ),
    ]
