# Generated by Django 5.0.9 on 2024-11-24 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0081_sitemappage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitemappage",
            options={"verbose_name": "Sitemap"},
        ),
    ]
