# Generated by Django 5.0.9 on 2024-12-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("numerique_gouv", "0085_alter_numeriquebasepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="offersentrypage",
            name="external_link",
            field=models.URLField(blank=True, verbose_name="External link"),
        ),
    ]
