# Generated by Django 5.0.10 on 2025-04-03 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_manager", "0053_cmsdsfrconfig_header_login_button"),
        ("numerique_gouv", "0089_alter_numeriquebasepage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumeriqueCatalogIndexPage",
            fields=[
                (
                    "catalogindexpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content_manager.catalogindexpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Numerique catalog index page",
            },
            bases=("content_manager.catalogindexpage",),
        ),
    ]
