# Generated by Django 5.0.10 on 2025-06-10 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("numerique_gouv", "0093_alter_numeriquebasepage_body_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="numeriquebasepage",
            name="header_cta_label",
        ),
        migrations.RemoveField(
            model_name="numeriquebasepage",
            name="header_cta_link",
        ),
    ]
