# Generated by Django 5.2.3 on 2025-06-20 16:09

from django.db import migrations, models
from wagtail_honeypot.models import get_honeypot_default


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_alter_formfield_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="formpage",
            name="honeypot",
            field=models.BooleanField(default=get_honeypot_default, verbose_name="Honeypot enabled"),
        ),
    ]
