# Generated by Django 5.0.6 on 2024-07-01 07:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0019_merge_20240618_1445"),
        ("blog", "0021_alter_blogentrypage_body_alter_blogindexpage_body"),
    ]

    operations = []
