# Generated by Django 5.0.6 on 2024-07-06 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0021_blogentrypage_header_cta_buttons_and_more"),
        ("blog", "0022_merge_20240701_0930"),
    ]

    operations = []
