# Generated by Django 5.0.8 on 2024-08-28 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0032_alter_blogentrypage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
    ]
