# Generated by Django 5.0.8 on 2024-08-28 20:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0032_alter_blogentrypage_body_alter_blogindexpage_body"),
        ("blog", "0033_alter_category_locale"),
    ]

    operations = []
