# Generated by Django 5.0.9 on 2024-09-13 07:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0034_category_sort_order_organization_sort_order_and_more"),
        ("blog", "0037_alter_blogentrypage_body"),
    ]

    operations = []
