# Generated by Django 5.0.9 on 2024-10-06 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0035_alter_blogentrypage_body_alter_blogindexpage_body_and_more"),
        ("blog", "0039_alter_blogentrypage_body"),
    ]

    operations = []
