# Generated by Django 5.0.9 on 2024-10-29 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0037_alter_blogentrypage_body_and_more"),
        ("blog", "0047_alter_blogentrypage_body"),
    ]

    operations = []
