# Generated by Django 5.0.9 on 2025-01-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0041_alter_blogentrypage_body_alter_blogindexpage_body_and_more"),
        ("blog", "0054_alter_blogentrypage_body"),
    ]

    operations = []
