# Generated by Django 5.0.9 on 2024-12-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0041_alter_blogentrypage_body_alter_blogindexpage_body_and_more"),
        ("blog", "0055_alter_blogindexpage_body"),
    ]

    operations = []
