# Generated by Django 5.0.9 on 2025-01-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0056_alter_blogentrypage_body"),
        ("blog", "0057_alter_blogentrypage_body_alter_blogindexpage_body"),
    ]

    operations = []
