# Generated by Django 5.0.10 on 2025-04-03 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0042_alter_blogentrypage_body_and_more"),
        ("blog", "0059_alter_blogentrypage_body_alter_blogindexpage_body"),
    ]

    operations = []
