# Generated by Django 5.0.10 on 2025-05-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0043_alter_blogentrypage_body_alter_blogindexpage_body_and_more"),
        ("blog", "0061_alter_blogentrypage_body_alter_blogindexpage_body"),
    ]

    operations = []
