# Generated by Django 5.0.10 on 2025-05-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0045_alter_blogentrypage_body_alter_blogindexpage_body_and_more"),
        ("blog", "0063_alter_blogentrypage_body_alter_blogindexpage_body"),
    ]

    operations = []
