# Generated by Django 5.0.10 on 2025-06-10 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0047_remove_blogentrypage_header_cta_label_and_more"),
        ("blog", "0065_alter_blogentrypage_body_alter_blogindexpage_body"),
    ]

    operations = []
