# Generated by Django 5.2.3 on 2025-06-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0048_blogentrypage_preview_image_and_more"),
        ("blog", "0066_merge_20250610_0814"),
    ]

    operations = []
